import pyautogui as gui
from time import sleep
from random import randint
gui.PAUSE = 0.1
gui.press("win")
gui.write("Opera Gx")
gui.press("enter")
sleep(1)
gui.press("win")
gui.write("GitHub Desktop")
gui.press("enter")
sleep(4)
gui.press("F11")

while True:
    nome = list()
    gui.click(x=165, y=16)
    gui.click(x=208, y=68)
    gui.click(x=281, y=106)
    for n in range(0, 15):
        nome.append(randint(0, 9))
    nome = str(nome)
    nome = nome.replace(" ", "")
    nome = nome.replace("]", "")
    nome = nome.replace("[", "")
    nome = nome.replace(",", "")
    gui.write(nome)
    sleep(0.5)
    gui.click(x=817, y=470)
    gui.write(nome)
    gui.click(x=847, y=526)
    gui.click(x=847, y=526)
    gui.click(x=847, y=526)
    gui.write(r"D:\Git e GitHub\GitHub-Teste")
    gui.click(x=787, y=559)
    gui.click(x=868, y=670)
    gui.click(x=898, y=709)
    gui.click(x=947, y=733)
    sleep(8)
    gui.click(x=1048, y=759)
    gui.click(x=1302, y=252)
    sleep(0.5)
    gui.click(x=764, y=601)
    sleep(0.1)
    gui.click(x=973, y=665)
    gui.hotkey("alt", "tab")
    sleep(2)
    gui.click(x=296, y=52)
    gui.write(r"https://github.com/Conta-Teste-AthosFB")
    gui.press("enter")
    sleep(4)
    gui.click(x=884, y=175)
    sleep(4)
    gui.click(x=1550, y=313)
    gui.hotkey("alt", "tab")
